events {}

http {
    include mime.types;

    upstream api {
        server ben-be-api:7001;
    }

    server {
        listen 80;

        include /etc/nginx/mime.types;

        root   /home/;

        location /ben/records {
            proxy_pass http://api/ben/records/;
        }
    }
}
