events {}

http {
    resolver 127.0.0.11 valid=30s;
    include mime.types;

    server {
        listen 80;

        include /etc/nginx/mime.types;

        root   /home/;

        location /new-ben {
            set $api http://new-ben-be-api:7001;
            proxy_pass $api$uri$is_args$args;
        }

        # WebSocket
        location /new-ben/ws {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            set $api http://new-ben-be-api:7001;
            proxy_pass $api$uri$is_args$args;
        }
    }
}
